### ISSUE TITLE
Hex package

### ISSUE THREAD

**Issue by lessless** [nathanjohnson320/httpdigest#3]
Hello @nathanjohnson320,

Thanks again for the good work on this library. Can you please publish it as a Hex package https://hex.pm/docs/publish? 

The library that we did has it as a dependency and we can't publish until all dependencies are on the Hex.

Thanks.

**Comment by nathanjohnson320** [comment]
Sure thing, give me a few minutes and i'll have it up

**Comment by nathanjohnson320** [comment]
https://hex.pm/packages/httpdigest
